/**
* ddosmitigator API generated from ddosmitigator.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "BlacklistSrcFileJsonObject.h"
#include <regex>

namespace io {
namespace swagger {
namespace server {
namespace model {

BlacklistSrcFileJsonObject::BlacklistSrcFileJsonObject() {
  m_fileIsSet = false;
}

BlacklistSrcFileJsonObject::BlacklistSrcFileJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_fileIsSet = false;


  if (val.count("file")) {
    setFile(val.at("file").get<std::string>());
  }
}

nlohmann::json BlacklistSrcFileJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_fileIsSet) {
    val["file"] = m_file;
  }

  return val;
}

std::string BlacklistSrcFileJsonObject::getFile() const {
  return m_file;
}

void BlacklistSrcFileJsonObject::setFile(std::string value) {
  m_file = value;
  m_fileIsSet = true;
}

bool BlacklistSrcFileJsonObject::fileIsSet() const {
  return m_fileIsSet;
}

void BlacklistSrcFileJsonObject::unsetFile() {
  m_fileIsSet = false;
}




}
}
}
}
