apiVersion: v1
metadata:
  name: mvbdockersecret
  namespace: kube-system
data:
  .dockercfg: eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYXVyaWNpb3Zhc3F1ZXpiZXJuYWwiLCJwYXNzd29yZCI6Imlvdm5ldDc1MTQiLCJlbWFpbCI6Im1hdXJpY2lvdmFzcXVlemJlcm5hbEBnbWFpbC5jb20iLCJhdXRoIjoiYldGMWNtbGphVzkyWVhOeGRXVjZZbVZ5Ym1Gc09tbHZkbTVsZERjMU1UUT0ifX0=
kind: Secret
type: kubernetes.io/dockercfg
---
