/**
* ddosmitigator API
* ddosmitigator API generated from ddosmitigator.yang
*
* OpenAPI spec version: 1.0.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* BlacklistDstInterface.h
*
*
*/

#pragma once

#include "../serializer/BlacklistSrcFileJsonObject.h"


using namespace io::swagger::server::model;

class BlacklistSrcFileInterface {
public:

  virtual void update(const BlacklistSrcFileJsonObject &conf) = 0;
  virtual BlacklistSrcFileJsonObject toJsonObject() = 0;

  /// <summary>
  /// Absolute path of blacklist file
  /// </summary>
  virtual std::string getFile() = 0;
};

